### ISSUE TITLE
[BUG]: Automatic Refresh 

### ISSUE THREAD

**Issue by jim4067** [SuperteamDAO/earn#526] opened 2024-04-01 12:45 UTC
## Expected Behavior
The web page should not automatically refresh itself 

## Actual Behavior
The webapp keeps refreshing itself when applying for a bounty, resulting in resetting the form I have filled. 

## Steps to Reproduce the Problem

1. Go to the earn website
2. Find and project and try to fill in the details and wait for a short while. The web page will refresh itself resulting in loss of all details you had filled.

## ENVIRONMENT 
**Broswer:**  Brave Browser 123.1.64.113
**OS:** Pop OS

**Comment by Mayank1170** [comment] 2024-06-04 19:43
gm @jim4067  
I couldn't reproduce the issue on my end, everything works normally. Could you provide more details or check again?

**Comment by jim4067** [comment] 2024-06-06 09:15
GM @Mayank1170, It might be the extensions installed, since this error only happens when I am on Brave. Let me try to get a screen recording over the weekend when it happens.

**Comment by a20hek** [comment] 2024-06-10 23:18
closing since we cant seem to replicate this issue

**Closed by a20hek** 2024-06-10 23:18 UTC
